//! On-chain parity: drives `QuayVenue` exactly like Titan's router would —
//! from nothing but raw account blobs — and asserts `quote()` reproduces what
//! the on-chain program actually paid for every recorded swap.
//!
//! Fixtures live in `../fixtures/*.json` and are generated by the litesvm
//! suite (`onchain/tests-litesvm/tests/adapter_fixtures.rs`) by executing
//! real swaps against the compiled program. Each fixture carries the full
//! account set at a snapshot plus `(side, amount_in, actual amount_out)` for
//! an amount sweep on both sides — `out: null` means the on-chain swap
//! FAILED, and the adapter must refuse to quote it (or quote zero output).

use std::collections::HashMap;
use std::str::FromStr;

use async_trait::async_trait;
use quay_aggregator_titan::QuayVenue;
use solana_account::Account;
use solana_pubkey::Pubkey;
use titan_integration_template::account_caching::{AccountCacheError, AccountsCache};
use titan_integration_template::trading_venue::{
    FromAccount, QuoteRequest, SwapType, TradingVenue,
};

const SIDE_SELL_BASE: u8 = 0;

/// Fixed-map `AccountsCache` — what Titan's docs call a "test harness using
/// fixed HashMaps". Stands in for their RPC-backed cache.
struct MapCache(HashMap<Pubkey, Account>);

#[async_trait]
impl AccountsCache for MapCache {
    async fn get_account(&self, pubkey: &Pubkey) -> Result<Option<Account>, AccountCacheError> {
        Ok(self.0.get(pubkey).cloned())
    }

    async fn get_accounts(
        &self,
        pubkeys: &[Pubkey],
    ) -> Result<Vec<Option<Account>>, AccountCacheError> {
        Ok(pubkeys.iter().map(|k| self.0.get(k).cloned()).collect())
    }
}

fn b64_decode(s: &str) -> Vec<u8> {
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD
        .decode(s)
        .expect("valid base64 in fixture")
}

struct Fixture {
    strategy: Pubkey,
    base_mint: Pubkey,
    quote_mint: Pubkey,
    accounts: HashMap<Pubkey, Account>,
    /// `(side, amount_in, Some(actual_out) | None-if-on-chain-failed)`
    swaps: Vec<(u8, u64, Option<u64>)>,
}

fn load_fixture(name: &str) -> Fixture {
    let path = format!("{}/../fixtures/{name}.json", env!("CARGO_MANIFEST_DIR"));
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {path}: {e} — regenerate with the litesvm suite"));
    let v: serde_json::Value = serde_json::from_str(&raw).expect("valid fixture JSON");

    let pk = |field: &str| Pubkey::from_str(v[field].as_str().expect(field)).expect(field);
    let accounts = v["accounts"]
        .as_array()
        .expect("accounts array")
        .iter()
        .map(|a| {
            let key = Pubkey::from_str(a["pubkey"].as_str().expect("pubkey")).expect("pubkey");
            let account = Account {
                lamports: a["lamports"].as_u64().expect("lamports"),
                data: b64_decode(a["data_b64"].as_str().expect("data_b64")),
                owner: Pubkey::from_str(a["owner"].as_str().expect("owner")).expect("owner"),
                executable: false,
                rent_epoch: 0,
            };
            (key, account)
        })
        .collect();
    let swaps = v["swaps"]
        .as_array()
        .expect("swaps array")
        .iter()
        .map(|s| {
            (
                s["side"].as_u64().expect("side") as u8,
                s["amount_in"].as_u64().expect("amount_in"),
                s["out"].as_u64(),
            )
        })
        .collect();

    Fixture {
        strategy: pk("strategy"),
        base_mint: pk("base_mint"),
        quote_mint: pk("quote_mint"),
        accounts,
        swaps,
    }
}

/// Full integrator flow for one fixture: construct from the raw strategy
/// account, `update_state()` through an `AccountsCache`, then `quote()`
/// every recorded swap and compare against the on-chain truth.
async fn assert_parity(name: &str) {
    let f = load_fixture(name);
    let strategy_account = f
        .accounts
        .get(&f.strategy)
        .unwrap_or_else(|| panic!("fixture {name} missing strategy account"))
        .clone();

    let mut venue =
        QuayVenue::from_account(&f.strategy, &strategy_account).expect("from_account");

    // Every pubkey the venue requests must be in the fixture — otherwise the
    // generator's account list has drifted from the adapter's.
    let wanted = venue
        .get_required_pubkeys_for_update()
        .expect("required pubkeys");
    for k in &wanted {
        assert!(
            f.accounts.contains_key(k),
            "fixture {name} missing required account {k}"
        );
    }

    let cache = MapCache(f.accounts.clone());
    venue.update_state(&cache).await.expect("update_state");
    assert!(venue.initialized(), "fixture {name}: venue uninitialized after update_state");

    for (side, amount_in, expected_out) in &f.swaps {
        let (input_mint, output_mint) = if *side == SIDE_SELL_BASE {
            (f.base_mint, f.quote_mint)
        } else {
            (f.quote_mint, f.base_mint)
        };
        let quote = venue.quote(QuoteRequest {
            input_mint,
            output_mint,
            amount: *amount_in,
            swap_type: SwapType::ExactIn,
        });

        match expected_out {
            Some(out) => {
                let q = quote.unwrap_or_else(|e| {
                    panic!(
                        "fixture {name}: on-chain swap (side {side}, in {amount_in}) paid {out} \
                         but the adapter refused to quote it: {e}"
                    )
                });
                assert_eq!(
                    q.expected_output, *out,
                    "fixture {name}: side {side}, in {amount_in} — adapter quoted \
                     {} but the program paid {out}",
                    q.expected_output
                );
                assert_eq!(q.amount, *amount_in, "fixture {name}: consumed-amount mismatch");
                assert!(
                    !q.not_enough_liquidity,
                    "fixture {name}: spurious not_enough_liquidity on a swap that filled"
                );
            }
            None => {
                if let Ok(q) = quote {
                    assert_eq!(
                        q.expected_output, 0,
                        "fixture {name}: side {side}, in {amount_in} FAILED on-chain but the \
                         adapter quoted out {} — routers would build doomed transactions",
                        q.expected_output
                    );
                }
            }
        }
    }
}

#[tokio::test]
async fn parity_flat() {
    assert_parity("flat").await;
}

#[tokio::test]
async fn parity_spread_fee() {
    assert_parity("spread_fee").await;
}

#[tokio::test]
async fn parity_exact_fee() {
    assert_parity("exact_fee").await;
}

#[tokio::test]
async fn parity_one_sided() {
    assert_parity("one_sided").await;
}
